MyShop/MyShopK6/Controllers/HangHoaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MyShopK6.Models;

namespace MyShopK6.Controllers
{
    public class HangHoaController : Controller
    {
        private readonly IMapper mapper;
        private readonly MyDbContext ctx;
        public HangHoaController(MyDbContext db, IMapper map)
        {
            ctx = db; mapper = map; 
        }
        public IActionResult Index(int? id)
        {
            var dsHangHoa = ctx.HangHoas.AsQueryable();
            if(id.HasValue)
            {
                dsHangHoa = dsHangHoa.Where(p => p.MaLoai == id);
            }

            //map HangHoa ---> HangHoaView
            var hangHoas = mapper.Map<List<HangHoaView>>(dsHangHoa.ToList());

            if (id.HasValue)
            {
                Loai loai = ctx.Loais.SingleOrDefault(p => p.MaLoai == id.Value);
                ViewBag.Loai = loai;
            }

            return View(hangHoas);
        }

        public IActionResult ChiTiet(int id)
        {
            HangHoa hh = ctx.HangHoas.SingleOrDefault(p => p.MaHh == id);
            if(hh != null)
            {
                HangHoaChiTiet hhct = mapper.Map<HangHoaChiTiet>(hh);

                return View(hhct);
            }

            return RedirectToAction(controllerName: "Home", actionName: "Error");
        }

        [Route("{loai}/{url}")]
        public IActionResult ChiTietHh(string loai, string url)
        {
            HangHoa hh = ctx.HangHoas.SingleOrDefault(p => p.TenHhSeoUrl == url);
            if (hh != null)
            {
                HangHoaChiTiet hhct = mapper.Map<HangHoaChiTiet>(hh);

                return View("ChiTiet", hhct);
            }

            return RedirectToAction(controllerName: "Home", actionName: "Error");
        }
    }
}

MyShop/MyShopK6/Views/Shared/Components/MenuLoai/Default.cshtml
@*File ~/Views/Shared/Components/MenuLoai/Default.cshtml*@
@model IEnumerable<Loai>
@{
    var dsLoaiCha = Model.Where(p => p.MaLoaiCha == null);
}

<ul class="menu-items col-xs-12">
    @foreach (var lo in dsLoaiCha)
    {
        var dsLoaiCon = Model.Where(p => p.MaLoaiCha == lo.MaLoai);
        <li class="menu-item depth-1 menucol-1-3 ">
            <div class="title title_font"> <a href="#">@lo.TenLoai</a></div>
            <ul class="submenu">
                @foreach (var loc in dsLoaiCon)
                {
                    <li class="menu-item">
                        <div class="title"> <a asp-controller="HangHoa" asp-action="Index" asp-route-id="@loc.MaLoai">@loc.TenLoai</a></div>
                    </li>
                }
            </ul>
        </li>
    }
</ul>